primes:
	g++ -std=c++11 -fopenmp primeOMP.cpp -o primes



life:
	g++ -std=c++11 -fopenmp Game_Of_Life_OpneMP.cpp -o life



floyd:
	gcc -std=c++11 -fopenmp floyd.c -o floyd



floyd_omp: 
	gcc -std=c++11 -fopenmp floydOMP.c -o floydomp



floyd_tile:
	gcc -std=c++11 -fopenmp floyd_tile.c -o floydtile



floyd_tile_omp: 
	gcc -std=c++11 -fopenmp floyd_tile_OMP.c -o floydtileomp
