primes:
	g++ -std=c++11 -fopenmp primeOMP.cpp -o primes



life:
	gcc -fopenmp gameOfLifeOMP.c -o life



floyd_omp: 
	gcc -fopenmp floydOMP.c -o floydomp



floyd_tile_omp: 
	gcc -fopenmp floyd_tile_OMP.c -o floydtileomp
