primes:
	g++ -std=c++11 -fopenmp primeOMP.cpp -o primes



life:
	g++ -std=c++11 -fopenmp Game_Of_Life_OpneMP.cpp -o life



floyd_omp: 
	gcc -fopenmp floydOMP.c -o floydomp



floyd_tile_omp: 
	gcc -fopenmp floyd_tile_OMP.c -o floydtileomp
